import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async={false} defer={false}></script>
      </head>
      <body>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_SIGN_IN_CLIENT_ID}>
          <div className="min-h-screen flex flex-col">
            <Navbar />
            {children}
          </div>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
